PUBLISHABLE_KEY: 'pk_live_AvHmFbfRqNrERQTF2TDKiNQx'
SECRET_KEY: 'sk_live_ItEEOFihFlNFHjobIKbpuFVa'

SENDGRID_USERNAME: 'apikey'
SENDGRID_PASSWORD: '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'

API_KEY: '04caff75e1ded2ea72c14a72c9f164e5'
API_SECRET: 'eb61e5250dafc503ccbb15800c01f321'